### ISSUE TITLE
Query on the labels of .npy file

### ISSUE THREAD

**Issue by OmPrasad93** [yuboxie/meed2#1]
Hi,

I was going through the data folder and opened the uttr_emots.npy in the train folder of ED dataset. While I understand that they are probability distributions of the 41 classes , is it possible to provide an order for them, or if I can say a mapping of the classes to the index. Or is it safe to assume that the distributions follow the same order as the **Figure 2: Distribution of emotions/intents in the emotional dialogs in OpenSubtitles** provided within the paper?

**Comment by yuboxie** [comment]
Hi,

Thanks for pointing out. I just uploaded the labels. Please see "emo_labels.txt".
