### ISSUE TITLE
Paper reproduction results 

### ISSUE THREAD

**Issue by P2Axelrod** [yuboxie/meed2#2]
The classifier accuracy on the EmpatheticDialogues test set is only 35.20% when i use your checkpoint of the predict_emo. It doesn't have the precision that you have in your paper. What do you think might have caused this. I am looking forward to your reply.

**Comment by yuboxie** [comment]
Hi,
We calculated the weighted precision of MEED2 (OS->ED) on ED, and the score is 0.2660. We didn't report accuracy scores.

**Comment by P2Axelrod** [comment]
I am very glad to receive your reply, but i mean you claimed in section 3.2, paragraph 2  : "The classifier achieved an accuracy of 65.88% on the EmpatheticDialogues test set. "

**Comment by yuboxie** [comment]
Actually that is the emotion classifier we used to label each utterance in the OS dataset. The classifier you ran is the response emotion/intent predictor in the MEED2 model, which predicts the emotion/intent of next utterance (the reply to be generated).

**Comment by P2Axelrod** [comment]
I'm glad you solved my doubts. Can you open source the code of your emotion classifier？Thank you very much!

**Comment by yuboxie** [comment]
We have an updated version of this emotion classifier, which you can find here:
https://github.com/anuradha1992/EDOS/tree/main/Scripts/Dialogue%20emotion%20classifier

**Comment by P2Axelrod** [comment]
Thank you very much for your work. I wish you happy every day!
